import Head from "next/head";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import { Footer } from "@/components/Footer";
import Main from "@/components/Main";
import Header from "@/components/Header";
import { useCallback, useEffect, useState } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  const [count, setCount] = useState(1);
  const [text, setText] = useState("");
  const [array, setArray] = useState([1, 2, 3]);

  const handleChange = (e) => {
    setText(e.target.value.trim());
  }

  const handleAdd = useCallback(() => {
    setArray((prevArray) => {
      if(prevArray.some(item => item === text)) {
        return prevArray
      }
      // const newArray = [...prevArray, text]
      return [...prevArray, text];
    });

    setText('')
  }, [text])

  const handleClick = useCallback((e) => {
    console.log(count)
    if(count < 10) {
      setCount((prevCount) => prevCount + 1);  
    }


    // setCount((prevCount) => prevCount + 1);
  }, [count])
  
  useEffect(() => {
    document.body.style.backgroundColor = "lightblue";
    return () => {
      document.body.style.backgroundColor = "";
    };
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <Header />
        <h1>{count}</h1>
        <button href="/about" onClick={handleClick}>
          ボタン
        </button>
        <input type="text" value={text} onChange={(e) => handleChange(e)} />
        <button onClick={handleAdd}>追加</button>
        <ul>
          {
            array.map((item) => {
              return <li key={item}>{item}</li>
            })}
        </ul>
        <Main page="index" />
        <Footer />
      </div>
    </>
  );
}
